package neu.edu.entity;
// Generated 10 Dec, 2017 5:27:37 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Servicecompletion generated by hbm2java
 */
@Entity
@Table(name = "servicecompletion", catalog = "crowdfunding")
public class Servicecompletion implements java.io.Serializable {

	private Integer serviceCompletionId;
	private Servicebid servicebid;
	private int progress;
	private Date date;
	private String description;

	public Servicecompletion() {
	}

	public Servicecompletion(Servicebid servicebid, int progress) {
		this.servicebid = servicebid;
		this.progress = progress;
	}

	public Servicecompletion(Servicebid servicebid, int progress, Date date, String description) {
		this.servicebid = servicebid;
		this.progress = progress;
		this.date = date;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_completion_id", unique = true, nullable = false)
	public Integer getServiceCompletionId() {
		return this.serviceCompletionId;
	}

	public void setServiceCompletionId(Integer serviceCompletionId) {
		this.serviceCompletionId = serviceCompletionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_bid_id", nullable = false)
	public Servicebid getServicebid() {
		return this.servicebid;
	}

	public void setServicebid(Servicebid servicebid) {
		this.servicebid = servicebid;
	}

	@Column(name = "progress", nullable = false)
	public int getProgress() {
		return this.progress;
	}

	public void setProgress(int progress) {
		this.progress = progress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
