package neu.edu.entity;
// Generated 10 Dec, 2017 5:27:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "crowdfunding")
public class Service implements java.io.Serializable {

	private Integer serviceId;
	private Project project;
	private String text;
	private Integer maxAmt;
	private Set<Servicebid> servicebids = new HashSet<Servicebid>(0);

	public Service() {
	}

	public Service(Project project) {
		this.project = project;
	}

	public Service(Project project, String text, Integer maxAmt, Set<Servicebid> servicebids) {
		this.project = project;
		this.text = text;
		this.maxAmt = maxAmt;
		this.servicebids = servicebids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_id", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "max_amt")
	public Integer getMaxAmt() {
		return this.maxAmt;
	}

	public void setMaxAmt(Integer maxAmt) {
		this.maxAmt = maxAmt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<Servicebid> getServicebids() {
		return this.servicebids;
	}

	public void setServicebids(Set<Servicebid> servicebids) {
		this.servicebids = servicebids;
	}

}
