package neu.edu.entity;
// Generated 10 Dec, 2017 5:27:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Startup generated by hbm2java
 */
@Entity
@Table(name = "startup", catalog = "crowdfunding")
public class Startup implements java.io.Serializable {

	private Integer startupId;
	private Category category;
	private Location location;
	private User user;
	private String companyName;
	private String about;
	private String contactPerson;
	private String phoneNumber;
	private Set<Servicebid> servicebids = new HashSet<Servicebid>(0);

	public Startup() {
	}

	public Startup(Category category, Location location, User user) {
		this.category = category;
		this.location = location;
		this.user = user;
	}

	public Startup(Category category, Location location, User user, String companyName, String about,
			String contactPerson, String phoneNumber, Set<Servicebid> servicebids) {
		this.category = category;
		this.location = location;
		this.user = user;
		this.companyName = companyName;
		this.about = about;
		this.contactPerson = contactPerson;
		this.phoneNumber = phoneNumber;
		this.servicebids = servicebids;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "startup_id", unique = true, nullable = false)
	public Integer getStartupId() {
		return this.startupId;
	}

	public void setStartupId(Integer startupId) {
		this.startupId = startupId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "company_name", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "about")
	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	@Column(name = "contact_person", length = 45)
	public String getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(String contactPerson) {
		this.contactPerson = contactPerson;
	}

	@Column(name = "phone_number", length = 45)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "startup")
	public Set<Servicebid> getServicebids() {
		return this.servicebids;
	}

	public void setServicebids(Set<Servicebid> servicebids) {
		this.servicebids = servicebids;
	}

}
