package neu.edu.entity;
// Generated 10 Dec, 2017 5:27:37 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Testimonial generated by hbm2java
 */
@Entity
@Table(name = "testimonial", catalog = "crowdfunding")
public class Testimonial implements java.io.Serializable {

	private Integer testimonialId;
	private Project project;
	private User user;
	private String testimonial;
	private Date postDate;
	private Integer rating;

	public Testimonial() {
	}

	public Testimonial(Project project, User user) {
		this.project = project;
		this.user = user;
	}

	public Testimonial(Project project, User user, String testimonial, Date postDate, Integer rating) {
		this.project = project;
		this.user = user;
		this.testimonial = testimonial;
		this.postDate = postDate;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "testimonial_id", unique = true, nullable = false)
	public Integer getTestimonialId() {
		return this.testimonialId;
	}

	public void setTestimonialId(Integer testimonialId) {
		this.testimonialId = testimonialId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "testimonial")
	public String getTestimonial() {
		return this.testimonial;
	}

	public void setTestimonial(String testimonial) {
		this.testimonial = testimonial;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "post_date", length = 19)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "rating")
	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

}
