language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew test

after_success:
- mkdir codedeploy
- zip -r csye6225-fall2017.zip build/libs/ROOT.war restartTomcat.sh  appspec.yml infrastructure/aws/cloudwatch/awslogs.conf
- ls -al
- mv csye6225-fall2017.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- pwd
- ls -al
- pwd
before_deploy:
- cd ..
deploy:
- provider: s3
  access_key_id: $access_key
  secret_access_key: $secret_key
  local_dir: codedeploy
  bucket: $bucket_name
  region: us-east-1
  skip_cleanup: true
  all_branches: true
  on:
    branch: Assignment10
- provider: codedeploy
  access_key_id: $access_key
  bucket: $bucket_name
  key: csye6225-fall2017.zip
  bundle_type: zip
  application: JavaApplication
  deployment_group: JavaApplication
  region: us-east-1
  secret_access_key: $secret_key
  wait-until-deployed: true
  all_branches: true
  on:
      branch: Assignment10

notifications:
  email:
    recipients:
      - jain.rish@husky.neu.edu